/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package PBFT;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2014-12-1")
public class AskForTransaction implements org.apache.thrift.TBase<AskForTransaction, AskForTransaction._Fields>, java.io.Serializable, Cloneable, Comparable<AskForTransaction> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AskForTransaction");

  private static final org.apache.thrift.protocol.TField VIEWSTAMP_FIELD_DESC = new org.apache.thrift.protocol.TField("viewstamp", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField REPLICA_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("replicaID", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new AskForTransactionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new AskForTransactionTupleSchemeFactory());
  }

  public Viewstamp viewstamp; // required
  public int replicaID; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    VIEWSTAMP((short)1, "viewstamp"),
    REPLICA_ID((short)2, "replicaID");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // VIEWSTAMP
          return VIEWSTAMP;
        case 2: // REPLICA_ID
          return REPLICA_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __REPLICAID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.VIEWSTAMP, new org.apache.thrift.meta_data.FieldMetaData("viewstamp", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Viewstamp.class)));
    tmpMap.put(_Fields.REPLICA_ID, new org.apache.thrift.meta_data.FieldMetaData("replicaID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AskForTransaction.class, metaDataMap);
  }

  public AskForTransaction() {
  }

  public AskForTransaction(
    Viewstamp viewstamp,
    int replicaID)
  {
    this();
    this.viewstamp = viewstamp;
    this.replicaID = replicaID;
    setReplicaIDIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AskForTransaction(AskForTransaction other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetViewstamp()) {
      this.viewstamp = new Viewstamp(other.viewstamp);
    }
    this.replicaID = other.replicaID;
  }

  public AskForTransaction deepCopy() {
    return new AskForTransaction(this);
  }

  @Override
  public void clear() {
    this.viewstamp = null;
    setReplicaIDIsSet(false);
    this.replicaID = 0;
  }

  public Viewstamp getViewstamp() {
    return this.viewstamp;
  }

  public AskForTransaction setViewstamp(Viewstamp viewstamp) {
    this.viewstamp = viewstamp;
    return this;
  }

  public void unsetViewstamp() {
    this.viewstamp = null;
  }

  /** Returns true if field viewstamp is set (has been assigned a value) and false otherwise */
  public boolean isSetViewstamp() {
    return this.viewstamp != null;
  }

  public void setViewstampIsSet(boolean value) {
    if (!value) {
      this.viewstamp = null;
    }
  }

  public int getReplicaID() {
    return this.replicaID;
  }

  public AskForTransaction setReplicaID(int replicaID) {
    this.replicaID = replicaID;
    setReplicaIDIsSet(true);
    return this;
  }

  public void unsetReplicaID() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __REPLICAID_ISSET_ID);
  }

  /** Returns true if field replicaID is set (has been assigned a value) and false otherwise */
  public boolean isSetReplicaID() {
    return EncodingUtils.testBit(__isset_bitfield, __REPLICAID_ISSET_ID);
  }

  public void setReplicaIDIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __REPLICAID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case VIEWSTAMP:
      if (value == null) {
        unsetViewstamp();
      } else {
        setViewstamp((Viewstamp)value);
      }
      break;

    case REPLICA_ID:
      if (value == null) {
        unsetReplicaID();
      } else {
        setReplicaID((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case VIEWSTAMP:
      return getViewstamp();

    case REPLICA_ID:
      return Integer.valueOf(getReplicaID());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case VIEWSTAMP:
      return isSetViewstamp();
    case REPLICA_ID:
      return isSetReplicaID();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof AskForTransaction)
      return this.equals((AskForTransaction)that);
    return false;
  }

  public boolean equals(AskForTransaction that) {
    if (that == null)
      return false;

    boolean this_present_viewstamp = true && this.isSetViewstamp();
    boolean that_present_viewstamp = true && that.isSetViewstamp();
    if (this_present_viewstamp || that_present_viewstamp) {
      if (!(this_present_viewstamp && that_present_viewstamp))
        return false;
      if (!this.viewstamp.equals(that.viewstamp))
        return false;
    }

    boolean this_present_replicaID = true;
    boolean that_present_replicaID = true;
    if (this_present_replicaID || that_present_replicaID) {
      if (!(this_present_replicaID && that_present_replicaID))
        return false;
      if (this.replicaID != that.replicaID)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_viewstamp = true && (isSetViewstamp());
    list.add(present_viewstamp);
    if (present_viewstamp)
      list.add(viewstamp);

    boolean present_replicaID = true;
    list.add(present_replicaID);
    if (present_replicaID)
      list.add(replicaID);

    return list.hashCode();
  }

  @Override
  public int compareTo(AskForTransaction other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetViewstamp()).compareTo(other.isSetViewstamp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetViewstamp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.viewstamp, other.viewstamp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetReplicaID()).compareTo(other.isSetReplicaID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReplicaID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.replicaID, other.replicaID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("AskForTransaction(");
    boolean first = true;

    sb.append("viewstamp:");
    if (this.viewstamp == null) {
      sb.append("null");
    } else {
      sb.append(this.viewstamp);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("replicaID:");
    sb.append(this.replicaID);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (viewstamp != null) {
      viewstamp.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AskForTransactionStandardSchemeFactory implements SchemeFactory {
    public AskForTransactionStandardScheme getScheme() {
      return new AskForTransactionStandardScheme();
    }
  }

  private static class AskForTransactionStandardScheme extends StandardScheme<AskForTransaction> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, AskForTransaction struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // VIEWSTAMP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.viewstamp = new Viewstamp();
              struct.viewstamp.read(iprot);
              struct.setViewstampIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // REPLICA_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.replicaID = iprot.readI32();
              struct.setReplicaIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, AskForTransaction struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.viewstamp != null) {
        oprot.writeFieldBegin(VIEWSTAMP_FIELD_DESC);
        struct.viewstamp.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(REPLICA_ID_FIELD_DESC);
      oprot.writeI32(struct.replicaID);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AskForTransactionTupleSchemeFactory implements SchemeFactory {
    public AskForTransactionTupleScheme getScheme() {
      return new AskForTransactionTupleScheme();
    }
  }

  private static class AskForTransactionTupleScheme extends TupleScheme<AskForTransaction> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, AskForTransaction struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetViewstamp()) {
        optionals.set(0);
      }
      if (struct.isSetReplicaID()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetViewstamp()) {
        struct.viewstamp.write(oprot);
      }
      if (struct.isSetReplicaID()) {
        oprot.writeI32(struct.replicaID);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, AskForTransaction struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.viewstamp = new Viewstamp();
        struct.viewstamp.read(iprot);
        struct.setViewstampIsSet(true);
      }
      if (incoming.get(1)) {
        struct.replicaID = iprot.readI32();
        struct.setReplicaIDIsSet(true);
      }
    }
  }

}

