/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package PBFT;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ChineseCheckersOperation implements org.apache.thrift.TEnum {
  NO_OP(0),
  MOVE_PIECE(1),
  KICK_PLAYER(2),
  ADD_PLAYER(3);

  private final int value;

  private ChineseCheckersOperation(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ChineseCheckersOperation findByValue(int value) { 
    switch (value) {
      case 0:
        return NO_OP;
      case 1:
        return MOVE_PIECE;
      case 2:
        return KICK_PLAYER;
      case 3:
        return ADD_PLAYER;
      default:
        return null;
    }
  }
}
