/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package PBFT;


public enum Vote implements org.apache.thrift.TEnum {
  COMMIT(1),
  ABBORT(2);

  private final int value;

  private Vote(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Vote findByValue(int value) { 
    switch (value) {
      case 1:
        return COMMIT;
      case 2:
        return ABBORT;
      default:
        return null;
    }
  }
}
